version: '3.7'

services:
  http:
    build: .
    command: php -S 0.0.0.0:8080 -t http http/index.php
    env_file:
      - .env
    environment:
      docker: "true"
    ports:
      - "${SITE_HOST}:8080:8080"
    volumes:
      - .:/app
      - /app/vendor/
    links:
      - pgsql
      - memcached

  socket:
    build: .
    command: php socket/index.php
    env_file:
      - .env
    environment:
      docker: "true"
    ports:
      - "${SITE_HOST}:8000:8000"
    volumes:
      - .:/app
      - /app/vendor/
    links:
      - pgsql
      - memcached

  pgsql:
    image: postgres:11.0
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:5432:5432"

  memcached:
    image: sameersbn/memcached:1.5.6-2
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:11211:11211"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${SITE_HOST}:3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules/

# docker-compose up -d --build
