version: '3.7'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:8080:80"
    volumes:
      - .:/app
    links:
      - pgsql
      - memcached

  socket:
    build:
      context: .
      dockerfile: Dockerfile
#    command: php socket/index.php
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:8000:8000"
    volumes:
      - .:/app
    links:
      - pgsql
      - memcached

  pgsql:
    image: postgres:11.0
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:5432:5432"

  memcached:
    image: sameersbn/memcached:1.5.6-2
    env_file:
      - .env
    ports:
      - "${SITE_HOST}:11211:11211"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "${SITE_HOST}:80:80"
