<?php


namespace App\Infrastructure\Hydrator;


use App\Domain\ValueObject\IoMessageBody;

class IoMessageBodyHydrator extends AbstractHydrator
{
    /**
     * @inheritDoc
     * @param string|IoMessageBody $object
     *
     * @return IoMessageBody|object
     */
    public function hydrate(array $data, $object)
    {
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function extract($object)
    {
        // TODO: Implement extract() method.
    }
}
