<?php


namespace App\Infrastructure\Hydrator;


class IoMessageHydrator extends AbstractHydrator
{
    /**
     * @inheritDoc
     */
    public function hydrate(array $data, $object)
    {
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function extract($object)
    {
        // TODO: Implement extract() method.
    }
}
