### Logout
POST http://{{SITE_URL}}/auth/logout
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

### Sign Up
POST http://{{SITE_URL}}/auth/signUp
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
   "user": {
     "username": "str14111112211222122211",
     "email": "str1142111212112212211@user.ua",
     "lastName": "str",
     "firstName": "str",
     "password": "str"
   }
}

### Confirm email
PATCH http://{{SITE_URL}}/auth/confirm-email
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
   "token": "WLc1MN1k8Zfr"
}

### Login
POST http://{{SITE_URL}}/auth/login
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
  "user": {
    "username": "str1111211",
    "password": "str"
  }
}

### Add interests
PUT http://{{SITE_URL}}/api/interests
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
  "interests": [
    {
      "name": "bla"
    },
    {
      "name": "kek"
    }
  ]
}

### Users search
GET http://{{SITE_HOST}}/api/users?username=user&
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
  "where": {
    "username": "user",
    "location": "",
    "interests": [

    ],
    "": "",
  },
  "orderBy": {
    "username": "desc",
    "fameRate": "asc"
  }
}
