### Logout
POST http://{{SITE_URL}}/auth/logout
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

### Sign Up
POST http://{{SITE_URL}}/auth/signUp
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
   "user": {
     "username": "str111112123112122211",
     "email": "str2111214212122@user.ua",
     "lastName": "str",
     "firstName": "str",
     "password": "str"
   }
}

### Confirm email
PATCH http://{{SITE_URL}}/auth/confirm-email
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
   "token": "eCqujJvby2f6"
}

### Login
POST http://{{SITE_URL}}/auth/login
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
  "user": {
    "username": "str1111211",
    "password": "str"
  }
}

### Add interests
PUT http://{{SITE_URL}}/api/interests
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1

{
  "interests": [
    {
      "name": "bla"
    },
    {
      "name": "kek"
    }
  ]
}

### Users search
GET http://{{SITE_URL}}/api/users?username=user&orderby_desc[0]=username&orderby_asc[1]=kek
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=1
